docker-build:
  image: docker:latest
  stage: build
  tags:
    - docker
  services:
    - DevOps-site
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag="0.0.1"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "vesves4/pptt:0.0.1" .
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
