stages:
  - build
  - deploy
  
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t paolonayednov/dev:0.1 .
    - docker push paolonaydenov/dev:0.1
  tags:
    - docker
  only:
    - main

deploy:
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_IMAGE: "paolonaydenov/dev:0.1"
  script:
    - docker pull "paolonaydenov/dev:0.1"
    - docker run -d --name devops -p 5173:5173 "$DOCKER_IMAGE"
  tags: 
    - docker
  only:
    - main
