stages:
  - build
  - deploy
before_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  tags:
    - test docker shell
  only:
    - main

deploy:
  stage: deploy
  image: docker:latest
  script:
    - docker pull "$DOCKER_IMAGE"
    - docker run -d --name devops -p 5173:5173 "$DOCKER_IMAGE"
  tags: 
    - test docker shell
  only:
    - main
